name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sadadYes'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        
    - name: Generate requirements files
      run: |
        # Create requirements files for different environments
        echo "-e ." > requirements.in
        echo "-e .[dev]" > requirements-dev.in
        echo "-e .[test]" > requirements-test.in
        
        pip-compile requirements.in
        pip-compile requirements-dev.in
        pip-compile requirements-test.in
        
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json --output safety-report.json || true
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "Update dependencies"
        body: |
          ## Dependency Updates
          
          This PR updates the project dependencies to their latest versions.
          
          ### Changes:
          - Updated requirements files
          - Security vulnerability check included
          
          Please review the changes and ensure all tests pass before merging.
        branch: update-dependencies
        delete-branch: true
